deck.source-language=EN
deck.target-language=FI

spring.profiles.active=text

spring.datasource.url=jdbc:mysql://localhost/wordlist

spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}